-- People

INSERT INTO People (person, createdAt, updatedAt) VALUES ('Eddard "Ned" Stark', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Robert Baratheon', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Jaime Lannister', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Catelyn Stark', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Cersei Lannister', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Daenerys Targaryen', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Jorah Mormont', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Viserys Targaryen', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Jon Snow', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Robb Stark', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Sansa Stark', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Arya Stark', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Theon Greyjoy', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Bran Stark', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Joffrey Baratheon', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Sandor "The Hound" Clegane', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Tyrion Lannister', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Petyr "Littlefinger" Baelish', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Davos Seaworth', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Samwell Tarly', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Stannis Baratheon', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Melisandre', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Jeor Mormont', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Bronn', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Varys', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Shae', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Margaery Tyrell', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Tywin Lannister', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Talisa Maegyr', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Ygritte', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Gendry', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Tormund Giantsbane', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Brienne of Tarth', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Ramsay Bolton', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Gilly', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Daario Naharis', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Missandei', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Tommen Baratheon', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Ellaria Sand', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Jaqen H\'ghar', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Roose Bolton', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('The High Sparrow', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Grey Worm', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Renly Baratheon', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Ros', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Luwin', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Hodor', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Osha', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Aemon', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Lysa Arryn', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Robin Arryn', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Rodrik Cassel', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Lancel Lannister', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Myrcella Lannister', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Rickon Stark', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Shireen Baratheon', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Oberyn Martell', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Drogo', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Jojen Reed', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Mance Rayder', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Thoros of Myr', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Meera Reed', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Loras Tyrell', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Myrcella Baratheon', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Xaro Xhoan Daxos', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Yara Greyjoy', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Doran Martell', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('High Sparrow', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Barristan Selmy', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Olenna Tyrell', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Pycelle', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Podrick Payne', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Alliser Thorne', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Eddison Tollett', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Gregor Clegane', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Waif', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Euron Greyjoy', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Beric Dondarrion', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('Walder Frey', NOW(), NOW());
INSERT INTO People (person, createdAt, updatedAt) VALUES ('The Night King', NOW(), NOW());

-- House

INSERT INTO Houses (House, createdAt, updatedAt) VALUES ('Stark', NOW(), NOW());
INSERT INTO Houses (House, createdAt, updatedAt) VALUES ('Lannister', NOW(), NOW());
INSERT INTO Houses (House, createdAt, updatedAt) VALUES ('Baratheon of Kings Landing', NOW(), NOW());
INSERT INTO Houses (House, createdAt, updatedAt) VALUES ('Baratheon of Dragonstone', NOW(), NOW());
INSERT INTO Houses (House, createdAt, updatedAt) VALUES ('Tyrell', NOW(), NOW());
INSERT INTO Houses (House, createdAt, updatedAt) VALUES ('Targaryen', NOW(), NOW());
INSERT INTO Houses (House, createdAt, updatedAt) VALUES ('Martell', NOW(), NOW());

